version: '3.5'
services:
  authentication-service:
    container_name: authentication-service
    image: 192.168.1.69:5000/weatherstationproject/authentication-service:1.0.0
    ports:
      - "8090:80"
      - "1443:443"
    environment:
      - REACT_APP_AUTHENTICATION_SECRET="123456"
      - REACT_APP_AUDIENCE_SECRET="MySecret"
    volumes:
      - '/etc/timezone:/etc/timezone:ro'
      - '/etc/localtime:/etc/localtime:ro'
  gateway-service:
    depends_on:
      - authentication-service
    container_name: gateway-service
    image: 192.168.1.69:5000/weatherstationproject/gateway-service:1.0.0
    ports:
      - "8091:80"
      - "2443:443"
    environment:
      - REACT_APP_AUDIENCE_SECRET="MySecret"
    volumes:
      - '/etc/timezone:/etc/timezone:ro'
      - '/etc/localtime:/etc/localtime:ro'
  ambient-temperature-service:
    depends_on:
      - gateway-service
    container_name: ambient-temperature-service
    image: 192.168.1.69:5000/weatherstationproject/ambient-temperature-service:1.0.0
    ports:
      - "8092:80"
      - "3443:443"
    environment:
      - AUDIENCE_SECRET="MySecret"
      - SERVER="192.168.1.69"
      - DATABASE="weather_station_dev"
      - USER="dashboard_dev"
      - PASSWORD="Dashboard_Dev"
    volumes:
      - '/etc/timezone:/etc/timezone:ro'
      - '/etc/localtime:/etc/localtime:ro'
  air-parameter-service:
    depends_on:
      - gateway-service
    container_name: air-parameter-service
    image: 192.168.1.69:5000/weatherstationproject/air-parameter-service:1.0.0
    ports:
      - "8093:80"
      - "4443:443"
    environment:
      - AUDIENCE_SECRET="MySecret"
      - SERVER="192.168.1.69"
      - DATABASE="weather_station_dev"
      - USER="dashboard_dev"
      - PASSWORD="Dashboard_Dev"
    volumes:
      - '/etc/timezone:/etc/timezone:ro'
      - '/etc/localtime:/etc/localtime:ro'
  wind-measurements-service:
    depends_on:
      - gateway-service
    container_name: wind-measurements-service
    image: 192.168.1.69:5000/weatherstationproject/wind-measurements-service:1.0.0
    ports:
      - "8094:80"
      - "5443:443"
    environment:
      - AUDIENCE_SECRET="MySecret"
      - SERVER="192.168.1.69"
      - DATABASE="weather_station_dev"
      - USER="dashboard_dev"
      - PASSWORD="Dashboard_Dev"
    volumes:
      - '/etc/timezone:/etc/timezone:ro'
      - '/etc/localtime:/etc/localtime:ro'
  rainfall-service:
    depends_on:
      - gateway-service
    container_name: rainfall-service
    image: 192.168.1.69:5000/weatherstationproject/rainfall-service:1.0.0
    ports:
      - "8095:80"
      - "6443:443"
    environment:
      - AUDIENCE_SECRET="MySecret"
      - SERVER="192.168.1.69"
      - DATABASE="weather_station_dev"
      - USER="dashboard_dev"
      - PASSWORD="Dashboard_Dev"
    volumes:
      - '/etc/timezone:/etc/timezone:ro'
      - '/etc/localtime:/etc/localtime:ro'
  ground-temperature-service:
    depends_on:
      - gateway-service
    container_name: ground-temperature-service
    image: 192.168.1.69:5000/weatherstationproject/ground-temperature-service:1.0.0
    ports:
      - "8096:80"
      - "7443:443"
    environment:
      - AUDIENCE_SECRET="MySecret"
      - SERVER="192.168.1.69"
      - DATABASE="weather_station_dev"
      - USER="dashboard_dev"
      - PASSWORD="Dashboard_Dev"
    volumes:
      - '/etc/timezone:/etc/timezone:ro'
      - '/etc/localtime:/etc/localtime:ro'
  dashboard:
    container_name: dashboard
    image: 192.168.1.69:5000/weatherstationproject/dashboard:1.0.0
    ports:
      - "8097:80"
      - "8443:443"
    environment:
      - REACT_APP_AUTHENTICATION_SECRET="123456"
      - REACT_APP_ACCUWEATHER_LOCATION_NAME="Moralzarzal"
      - REACT_APP_WEATHER_API_HOST="https://localhost:44375"
      - REACT_APP_ACCU_WEATHER_API_KEY="agzy4UX4RlokbgSksCKR4ZVbcFAA6bvi"
      - REACT_APP_AUTHENTICATION_SERVICE_HOST="https://localhost:44394"
    volumes:
      - '/etc/timezone:/etc/timezone:ro'
      - '/etc/localtime:/etc/localtime:ro'